language: java
deploy:
  provider: heroku
  app: quiet-beach-80018
  api_key:
    secure: dtjEAjR5A6Hxqlx9mE0BR556y/DTmFVfd3AdjfTSbQnQH1zEH0V2fP3U4tMWhTNS4O03LmErtSa7uKcn31cPBNDvOOTErL+Ywwl5ndrZl03zi2yOPtkC/CMM4uGpvGKBmvjF2mzlP2XL4Kv79l/CgjbPQBu/KcbVpTmgl5NtolDRldspqssDyG89LOpSZp+auMZLNofzgHEar44mquk5COy1tQIsr7zZzPO5jOJmsaPksmd2Fh+HRrEm4H9UWUtsdSnugOmYHuw1i2VfgqeSTwj0emUygUMg7jdpbsNGvoYEwckOiFvRuzODwFbwTKCUL0IuS0dmiTzAfAuGUw1NyUwJ1J1ybuhuRacXzrFG67iZzLoiwrfKMA/BiqljumhowzxwIiSMW3HVei2QVlw6vsOL32IWXch7i6wCCd7Q4mu3nmwbfVup7Tq9DSDm3opSB1Sl/4aN3NEt0Y4X6jheQOb41oNE882FotqHUZk9qfrYQinFRGQDGF+fozvQht35xRWEFVrQXlsgtaVYGsEj9n/b6PwGCm5zMjIsFaYuvpnuQljCjx+D0K1F0TmZCnWrsU9JPeUZ1QeKbzG5Uv/4etA/9JR7yUHKmu920JHu7WYXFtM+m3CyM19ENqd7dYikWmK8AdtEAImszrwPEkFRRy8KbnsBxh4jakm8zKwurEU=
